# AnalysisTemplate: Tự chấm canary bằng success rate
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: demo
spec:
  metrics:
  - name: success-rate
    interval: 30s
    successCondition: result >= 0.90
    failureLimit: 10
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
        query: |
          scalar(
            sum(rate(flask_http_request_duration_seconds_count{namespace="demo",app="api",status!~"5.."}[2m]))
            /
            sum(rate(flask_http_request_duration_seconds_count{namespace="demo",app="api"}[2m]))
          )
