apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-db-secret
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: api-db-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: db-password
